### ISSUE TITLE
RSS Posts Links should be fully qualified.

### ISSUE THREAD

**Issue by darron** [bscott/golangflow#17]
As it means you can't click on the links in your reader - it thinks they're at the same domain name as the reader.

I've been working on a patch, but am having problems bending Buffalo to my will - will keep trying and submit when I have a moment.

**Comment by bscott** [comment]
@darron Thanks for willing to contribute, Which troubles are you having with Buffalo?

**Comment by markbates** [comment]
@darron https://github.com/bscott/golangflow/blob/master/actions/home.go#L47 shows usage of the app host. You can also get the host from the request.

**Comment by markbates** [comment]
In theory appending the host here https://github.com/bscott/golangflow/blob/master/actions/home.go#L63 should it.

**Comment by darron** [comment]
Yeah - I had tried a couple ways from App().Host to the context object - I
can see the Host.

I was getting a malformed URL with only a single slash after http:/ - it's
odd.

I took a look at gorilla/feeds to see if maybe there was a bug there - but
that seems to do it properly.

The frustration with Buffalo is in trying to get debug information out to
the logs. Nothing I would output seemed to show up.

Will try again on the plane to Gophercon tomorrow.

**Comment by markbates** [comment]
@darron I'm curious as to how you're trying to print stuff out.

This worked for me:

```go
	c.Logger().Debugf("host: %s", App().Host)
```

```
time="2017-07-11T09:48:06-04:00" level=debug msg="host: http://127.0.0.1:3000" method=GET params="{}" path="/rss" request_id=98e632ee05-c05154116e 
```

Also `fmt.Printf` works for me too.

How are you trying to log stuff?

Also, I updated the code with the following:

```go
Link:  &feeds.Link{Href: fmt.Sprintf("%s/posts/%s", App().Host, p.ID)},
```

And it worked no problem.

```xml
    <item>
      <title>Post 2</title>
      <link>http://127.0.0.1:3000/posts/c68c8f7c-fe30-48a1-a331-f4f7b33d7d8a</link>
      <description>content for 2</description>
      <author>DB Seed</author>
      <pubDate>Tue, 11 Jul 2017 09:50:47 +0000</pubDate>
    </item>
```

How are you trying to build the link?

**Comment by darron** [comment]
I was doing it pretty much the exact same way.

I thought that maybe there was some old/duplicate versions of software around - so I blew away all my old buffalo binaries, pulled this repo again and started from scratch:

```
export GOPATH="/Users/dfroese/go"
cd ~/go/src/github.com/bscott
git@github.com:bscott/golangflow.git
cd golangflow
go get -u -v github.com/gobuffalo/buffalo/buffalo
dep ensure
npm install
buffalo dev
```

This is the only change:

```
Link:        &feeds.Link{Href: fmt.Sprintf("%s/posts/%s", App().Host, p.ID)},
```

Now it totally works like it should - no more missing `/` in the `<link>`.

Thanks for the tip about `c.Logger()` - wasn't aware that was available.

I am not sure what happened there - but now it all seems to work.

Sorry for the false alarm / bug report - appreciate the help sorting it out.

**Comment by markbates** [comment]
No worries. Not sure what the mismatch was, but glad you got it working. :)

**Comment by darron** [comment]
Added a trivial PR to fix this.

**Comment by bscott** [comment]
Fixed and merged. Thanks @darron
