### ISSUE TITLE
Connecting to a Mysql db

### ISSUE THREAD

**Issue by hubyhuby** [bscott/golangflow#24]
Hi,
I have reconfigured database as in the attached yml to use mysql.
Also the database creation fails and still talks about " creating PostgreSQL database "
But in the MYSQL database it actually creates the database, but no tables are populated.

# buffalo db create -a
v3.51.3

created database golangflow_development
Usage:
  buffalo db create [flags]
...

ERRO[0000] Error: couldn't create database golangflow_test: error creating PostgreSQL database golangflow_test: pq: password authentication failed for user "postgres"

 -----------------------------------------------------------------------------------
/Documents/projects/src/github.com/bscott/golangflow# cat database.yml 
development:
  dialect: mysql
  database: golangflow_development
  user: test
  password: test
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/golangflow_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/golangflow_production?sslmode=disable"}}
root@-GE72-2QF: /Documents/projects/src/github.com/bscott/golangflow#

**Comment by hubyhuby** [comment]
I have installed postgres , which I am not comfortable at all with, to give it a try ...
No luck here aswell :(

I have created a user test with psswd test...
Using: "su test" and the password test it works in command line..I can type psql
Also the buffalo commande says it cannot creat the db:

buffalo db create -a
ERRO[0000] Error: couldn't create database golangflow_development: error creating PostgreSQL database golangflow_development: pq: password authentication failed for user "test"
-----
My database.yml

development:
  dialect: postgres
  database: golangflow_development
  user: test
  password: test
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:test@127.0.0.1:5432/golangflow_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:test@127.0.0.1:5432/golangflow_production?sslmode=disable"}}

**Comment by bscott** [comment]
@hubyhuby Did you set you Postgres User and Pass?

I use the creds below for local development, I also use `postgresapp` for Mac to manage local PostgreSQL.

```
 user: postgres
 password: postgres
```

**Comment by bscott** [comment]
@hubyhuby Ok, your very close, you have run the Pop migrations and set some Environment variables. I'm actually about to update the README with full details.

**Comment by hubyhuby** [comment]
Hi @bscott Thanks a lot
I suppose you ll get lots of noobs like me trying to make this example work (since it is on the example page).
I definitely think an advanced newbie readme would be great.
Sorry for bugging you with those basic questions.
Thanks a lot

**Comment by bscott** [comment]
@hubyhuby No problem!, I'm just about done writing up a new README, should b esimple to get up and running.

**Comment by hubyhuby** [comment]
Looks like we are missing the command " buffalo setup", which seems compulsory to get the assets...as I experienced it on my system.
https://github.com/gobuffalo/gothrecipe/issues/1

**Comment by bscott** [comment]
@hubyhuby Are you good to go?

**Comment by bscott** [comment]
Closing this for now, reopen if you need too.
